# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # require 'webmock/rspec'
  # WebMock.disable_net_connect!(allow_localhost: true)
  # config.before(:each) do
  #   stub_request(:get, "").
  #   with(
  #     headers: {
  #    'Accept'=>'*/*',
  #    'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
  #    'Host'=>'www.googleapis.com',
  #    'User-Agent'=>'Ruby'
  #     }).
  #   to_return(status: 200, body: '{
  #     "kind": "youtube#searchListResponse",
  #     "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/NACTh0IbBuzSNeMXjGh5hjxdeuc\"",
  #     "nextPageToken": "CDIQAA",
  #     "regionCode": "CA",
  #     "pageInfo": {
  #         "totalResults": 1000000,
  #         "resultsPerPage": 50
  #     },
  #     "items": [
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/KEOIqQ_fkE3ti-NxxzBYHcuN7HY\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "y6GcCjCb_m0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-06-14T12:22:24.000Z",
  #                 "channelId": "UCH6vXjt-BA7QHl0KnfL-7RQ",
  #                 "title": "Armchair Fan - Simon&#39;s Cat | SHORTS #80",
  #                 "description": "Simon\'s plan to watch the Football World Cup 2018 is ruined by his four legged armchair fan. Can you relate to this? COMMENT, LIKE & SHARE! Want to see ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/y6GcCjCb_m0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/y6GcCjCb_m0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/y6GcCjCb_m0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Simon\'s Cat",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/pC4HdbOLolrA2ELamQomjtaIbE4\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "SQUexpLULlw"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-10-06T10:10:49.000Z",
  #                 "channelId": "UC_D5hKQBzPc2Ilx2gMfl1oA",
  #                 "title": "CAT 80 to 99 Percentile. How to increase your score",
  #                 "description": "catexam #cat2019 #99percentile#catprep #mbaprep #c2cmentors C2C Mentors CAT & Other MBA Entrance Online Program Call 9920553559, 9022342214 Or ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/SQUexpLULlw/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/SQUexpLULlw/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/SQUexpLULlw/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ketankg C2C Mentors",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/VwvMUqk8Hlfbu9zPD9rXvf1l0Fw\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "tBV4ft6NeeY"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-09-17T15:34:57.000Z",
  #                 "channelId": "UCCj956IF62FbT7Gouszaj9w",
  #                 "title": "The lady with 80 cats - Cat Wars: Preview - BBC One",
  #                 "description": "Subscribe and to OFFICIAL BBC YouTube https://bit.ly/2IXqEIn Stream original BBC programmes FIRST on BBC iPlayer https://bbc.in/2J18jYJ Programme ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/tBV4ft6NeeY/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/tBV4ft6NeeY/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/tBV4ft6NeeY/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "BBC",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/GuL4ILjEFz9vJ3DwpW8DMf1gsWI\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "krHmjm2AqL0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-12-06T12:51:20.000Z",
  #                 "channelId": "UCjrG4n3cS6y45BfCJjp3boQ",
  #                 "title": "Colleges to Target for 70, 80 and 90th Percentile in CAT💲🤑",
  #                 "description": "In this video, we have compiled the list of Colleges to Target for 70, 80 & 90th Percentile and Cut-off, Fees, Avg. Salary and ROI of these colleges and their ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/krHmjm2AqL0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/krHmjm2AqL0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/krHmjm2AqL0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Cracku - MBA CAT Preparation",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/rR9IVswPQBChv7685dpvrEWWz1g\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "YgG9jg6Ml2A"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-04-21T11:13:59.000Z",
  #                 "channelId": "UCrS7LVKWs4YIJNWgW3cM6sw",
  #                 "title": "ARIA: 80 Sunreef Power Catamaran [Walkthrough]",
  #                 "description": "Sunreef Price, Specs + Photos: https://hubs.ly/H0pJlvH0 ARIA is located in Fort Lauderdale and is the first Sunreef 80 Power to be offered for sale on the ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/YgG9jg6Ml2A/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/YgG9jg6Ml2A/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/YgG9jg6Ml2A/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Denison Yachting",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/ZS0MHkb7lNOvr0Bo8p5mgAoBrRo\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "O3RjIKvOL5c"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-09-27T17:40:43.000Z",
  #                 "channelId": "UC_D5hKQBzPc2Ilx2gMfl1oA",
  #                 "title": "CAT 2018 | Verbal Ability | 80 Percentile Sure Shot Strategy",
  #                 "description": "CAT Verbal Ability 80 Percentile Sure Shot Strategy to crack VA cut off of all the IIMs. Watch this video to know CAT VA Paper Structure CAT 2016 & CAT 2017 ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/O3RjIKvOL5c/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/O3RjIKvOL5c/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/O3RjIKvOL5c/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ketankg C2C Mentors",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/lVNzJh_fpOyPRlSjkbKW-ffwjk0\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "At61fO2hCCE"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-01-10T18:53:12.000Z",
  #                 "channelId": "UCK9E37wm7FeGh1af9jiZHeg",
  #                 "title": "cat.80",
  #                 "description": "Casale sul sile cat.B80 Campionati Reg.Terza Prova cat.90 watch hd.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/At61fO2hCCE/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/At61fO2hCCE/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/At61fO2hCCE/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "bea franceschin",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/nDu447S89QoRscB6CZOCz3iPq4o\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "24DRTKKi9po"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2013-09-01T14:52:07.000Z",
  #                 "channelId": "UCRj5lRUWkIALJvNwBI58qyg",
  #                 "title": "Salto a ostacoli cat.80",
  #                 "description": "Lisa Bortolotto - Miu Miu San Daniele 30/08/13.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/24DRTKKi9po/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/24DRTKKi9po/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/24DRTKKi9po/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Max1987",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/Hq1S4XbXLbyZJvm0raNYeFJM85I\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "wP9XE489kVg"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-10-26T19:06:09.000Z",
  #                 "channelId": "UC-XyYZQKwuvQn_054LwxW1g",
  #                 "title": "How to get 80%ile in CAT. IIM Ahmedabad Certificates by Nov 30. D27",
  #                 "description": "CAT Task To join the paid program or WhatsApp groups: https://www.cetking.in/product/catturbo2/ 30 days to CAT Daily Tasks: 1. Numbers Remainder Theorm 3 ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/wP9XE489kVg/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/wP9XE489kVg/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/wP9XE489kVg/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ck cetking",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/1ylHg5CN5AoB4isdVTCU_kGs4GU\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "GfoHK7JB9DY"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-08-24T21:11:11.000Z",
  #                 "channelId": "UCtsDgYUt3fB10Z0w_byCBhQ",
  #                 "title": "Parque vs GEVS - CAT 80",
  #                 "description": "Video aportado por LUIS YIYO ANDRETTO, Famosa categoria 80 de Club Social y Deportivo Parque jugando contra GEVS en cancha de APV: Compuesta por ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/GfoHK7JB9DY/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/GfoHK7JB9DY/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/GfoHK7JB9DY/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Nacho Gimenez Jara",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/Qy_7rGOwKJT1UR9TW2tXxPpLaRg\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "85-Xqx0ZYE4"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-07-03T00:52:30.000Z",
  #                 "channelId": "UCWzrEEGhRsO9MgJmidIBxLA",
  #                 "title": "Cat  80",
  #                 "description": "",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/85-Xqx0ZYE4/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/85-Xqx0ZYE4/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/85-Xqx0ZYE4/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Hqsail Nboov",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/eULwdXTKP9OF3cUU2lrVHNeRkfA\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "4RDMIphKKTk"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2009-10-24T22:20:48.000Z",
  #                 "channelId": "UCmUng13gwl9jVHuAYb6hPvQ",
  #                 "title": "CC Catch  MEGAMIX  80s Disco.",
  #                 "description": "Hola !!! la Grandiosa musica de los 70,80 y 90´s fueron las mejores epocas , aunque a mi desgraciadamente no me toco vivir mas la de los 90,s ,, me es muy ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/4RDMIphKKTk/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/4RDMIphKKTk/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/4RDMIphKKTk/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "JuanPacci pino",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/m7QKNeP6m5ZFfBT5qBruSlLN-04\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "YkjUfYefqTM"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2013-01-29T02:58:33.000Z",
  #                 "channelId": "UCmJXxEx-M-CSvy4383qOIWg",
  #                 "title": "Yamaha Fat-Cat 80cc.",
  #                 "description": "My new to me yamaha fat cat, 80cc.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/YkjUfYefqTM/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/YkjUfYefqTM/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/YkjUfYefqTM/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Max Maruszewski",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/ZnwLF27xX5NEVJ2oJVocLXeRc38\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "8mwIRLhPJio"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2016-04-26T16:56:01.000Z",
  #                 "channelId": "UCx7YcWe3KTUZNCPWOPGE0hA",
  #                 "title": "Super Cat The (Wild Apache)  80s &amp;  90s Juggling  mix by djeasy",
  #                 "description": "Download Ful Mixtape http://tinyurl.com/wildapachie Support Djeasy (Donation Link) https://www.gofundme.com/jkw5a37g ((·▭· · ··· subscribe, ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/8mwIRLhPJio/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/8mwIRLhPJio/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/8mwIRLhPJio/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Djeasy MuzikRyder",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/KcIzQygyP8mARwCSuZ3HTUQicQw\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "KkmRV-sXcsI"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2017-11-09T17:32:17.000Z",
  #                 "channelId": "UC-XyYZQKwuvQn_054LwxW1g",
  #                 "title": "MBA Colleges at 80%ile + in CAT",
  #                 "description": "Colleges you can expect at CAT 80%ile INSTAGRAM LINK :- https://instagram.com/cetking.official?igshid=soefdp00pqas FACEBOOK LINK ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/KkmRV-sXcsI/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/KkmRV-sXcsI/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/KkmRV-sXcsI/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ck cetking",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/A2RM4OZI26zIn6NBwSl-Qv-rl7o\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "PHVHqhI_ROk"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-10-31T02:38:53.000Z",
  #                 "channelId": "UCPmiqbKUt3ap_7sSKstR3tA",
  #                 "title": "ਦੇਖੋ Canada &#39;ਚ 80 ਸਾਲਾ ਮੁਟਿਆਰਾਂ ਦੀ Cat Walk",
  #                 "description": "Latest News: Log on to http://tvpunjab.com/ Punjabi News ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਵੇਖਣ ਲਈ SUBSCRIBE ਕਰੋ TV Punjab ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/PHVHqhI_ROk/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/PHVHqhI_ROk/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/PHVHqhI_ROk/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "TV Punjab",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/RUxKuZ9ZhuK1FDXA39xIuyZD9lQ\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "OivjNVDe5gk"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2010-10-28T05:28:02.000Z",
  #                 "channelId": "UC8JXTFT29nnxsH3i8YfquHQ",
  #                 "title": "Cat Falls 80 FEET, and LIVES",
  #                 "description": "video uploaded from iphone, recorded off of television show MOST AMAZING VIDEOS, and this truly is one. I cat gets itself stuck in a pine tree 80 feet up, after 8 ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/OivjNVDe5gk/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/OivjNVDe5gk/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/OivjNVDe5gk/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "SlapDashMedia",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/-gh9uoYZlj8a7ukrUfglaXAG81o\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "TTNqwAUoMo8"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-03-15T10:01:33.000Z",
  #                 "channelId": "UCDywFDjEL1nUi13cb6mLn5w",
  #                 "title": "Cat 308E2 Excavator breaking rock with a Cat H80E hammer",
  #                 "description": "Caterpillar 308E2 track hoe breaking rock for a house foundation with a Cat H80E hammer. LET\'S CONNECT! God\'s Country\'s Accounts: ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/TTNqwAUoMo8/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/TTNqwAUoMo8/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/TTNqwAUoMo8/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "God\'s Country",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/NIDwxLJGrCZEOkEvfAcDodlGQZQ\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "UTjVOC8KgLM"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-04-21T23:59:48.000Z",
  #                 "channelId": "UCeL2LSl91k2VccR7XEh5IKg",
  #                 "title": "Rescue cat Grace gives birth for the last time!",
  #                 "description": "We broadcast the stories of our rescued cats, LIVE and uncensored, to raise awareness about the realities of cat overpopulation, and to inspire compassion.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/UTjVOC8KgLM/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/UTjVOC8KgLM/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/UTjVOC8KgLM/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "TinyKittens HQ",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/JMC8AvuNMQrlnwYpezlw73zbNDE\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "6ArscwR4Wn0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-01-09T13:40:24.000Z",
  #                 "channelId": "UCA17v3ENpnoN4MWo8sbmM6w",
  #                 "title": "What Colleges to apply based on CAT Percentile and Past Acads?",
  #                 "description": "BEST MBA COLLEGES TO APPLY BASED ON CAT 2018 PERCENTILE, Visit: https://online.2iim.com/top-mba-colleges-in-india/ We get one question a lot - an ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/6ArscwR4Wn0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/6ArscwR4Wn0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/6ArscwR4Wn0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "2IIM CAT Preparation",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/kIvO_8HgI7URQVBYFLlWGtc-U5g\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "vRU1X2ZzU7A"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-03-30T19:55:08.000Z",
  #                 "channelId": "UC43dNggCpwjKRBP-H_94Gzg",
  #                 "title": "Batman: The Bat and the Cat 80 Years of Romance - przegląd",
  #                 "description": "Wesprzyj kanał: https://tipanddonation.com/Pogadajmy_o_komiksach https://paypal.me/pogadajmyokomiksach?locale.x=pl_PL.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/vRU1X2ZzU7A/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/vRU1X2ZzU7A/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/vRU1X2ZzU7A/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Pogadajmy o komiksach",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/57BwHITgE4-TBGbGBFEQ9TZd5bU\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "2s1bVUQIaFc"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-05-16T09:38:53.000Z",
  #                 "channelId": "UCJNk9_2z6ki5VKYonWLaX9A",
  #                 "title": "猫の宝物✨【可愛い】【cat】＃80",
  #                 "description": "仕事帰りのお兄ちゃんの靴下は タレにとって宝物✨ ここは俺が守る❗️って退かない.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/2s1bVUQIaFc/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/2s1bVUQIaFc/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/2s1bVUQIaFc/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "タレちゃんねる",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/9xsWjEfKcFbklXjlJytdLnzdCzs\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "Lr59biySinI"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2016-11-10T04:45:17.000Z",
  #                 "channelId": "UCvf79fZ8AfV2eqVRHkIbIPQ",
  #                 "title": "Colleges with cut-offs between 80-90 percentile | CAT",
  #                 "description": "Researching probable colleges as well as their courses is an important exercise that any serious CAT aspirant should plan for. In this series we shall bring you ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/Lr59biySinI/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/Lr59biySinI/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/Lr59biySinI/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Endeavor Careers",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/NVlgqJUicTnIJxrqX26REYJBRgQ\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "ZI2dOdqUIcw"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2012-10-21T14:24:15.000Z",
  #                 "channelId": "UCuCJVNtmIZT0H8UQTXvTBQw",
  #                 "title": "versatile 550 with cat 80 scraper saskatchewan",
  #                 "description": "making the field ready for spring runoff.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/ZI2dOdqUIcw/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/ZI2dOdqUIcw/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/ZI2dOdqUIcw/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "gerardmarieketess",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/WkbpHbAeu4fywJZ6TMlZiDwZWTU\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "WIwuhs1EFOI"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2016-11-12T05:08:41.000Z",
  #                 "channelId": "UCvf79fZ8AfV2eqVRHkIbIPQ",
  #                 "title": "Colleges with cut-offs between 70-80 percentile | CAT",
  #                 "description": "Researching probable colleges as well as their courses is an important exercise that any serious CAT aspirant should plan for. In this series we shall bring you ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/WIwuhs1EFOI/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/WIwuhs1EFOI/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/WIwuhs1EFOI/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Endeavor Careers",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/5ZbPRt4VYZR4x6-dyhuQTINYSeo\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "vvz_D1oNwH0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2011-03-08T19:46:23.000Z",
  #                 "channelId": "UCd6hUaUIrRgjbN8AVZog61w",
  #                 "title": "Jet Cat P-80 SE start",
  #                 "description": "I just checked all the planes and engines+turbines for the next season. Wanted to smell Jet A-1... :) Jet Cat P-80 SE is so effortless even it has been untouched ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/vvz_D1oNwH0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/vvz_D1oNwH0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/vvz_D1oNwH0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "jcres75",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/f0expZejeYcYLwEZNGKI3Gf86Xw\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "PvqSm4SlsaA"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-01-08T06:22:45.000Z",
  #                 "channelId": "UCMjf6P1rYTP2S_WX-9rqACg",
  #                 "title": "Colleges Under 80-90 Percentile In CAT",
  #                 "description": "Website Link - https://www.learn4exam.com/ TOP 60 MBA COLLEGES - https://youtu.be/aZ_nvQOjBsI CAT FULL SYLLABUS - https://youtu.be/PAQcUA3-684 ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/PvqSm4SlsaA/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/PvqSm4SlsaA/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/PvqSm4SlsaA/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Learn4Exam",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/dO-S1kOYKhqi0EV2NEwenBDauZ4\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "OWgMLKeX-ZI"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-03-21T02:23:08.000Z",
  #                 "channelId": "UC-XyYZQKwuvQn_054LwxW1g",
  #                 "title": "CAT 80%iler. How many General SC OBC ST Scored more than 80%ile",
  #                 "description": "To buy CAT 2020 Programs Mocks Shortcuts Books: https://www.cetking.in/product-category/cet/ To buy CET 2021 Programs G Strategy Mocks Shortcuts: ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/OWgMLKeX-ZI/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/OWgMLKeX-ZI/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/OWgMLKeX-ZI/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ck cetking",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/dwiR5dTxWyAe0kgi1TfTyXrxYT8\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "eqHaU82tYMc"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-02-26T23:40:38.000Z",
  #                 "channelId": "UCMkX4l31Jhv7slKyYV9JEzQ",
  #                 "title": "BATMAN: THE BAT AND THE CAT: 80 YEARS OF ROMANCE DC ENGLISH 2020 HD 720p",
  #                 "description": "If you liked the comic, leave a like, leave me your opinion in the comments, share it with your friends and most importantly subscribe to my channel on YouTube.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/eqHaU82tYMc/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/eqHaU82tYMc/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/eqHaU82tYMc/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "COMIC PDF2",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/D7QN0K2TjWqYKCdn2cyBWbZEGcc\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "Zbcvx2Ge9x4"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-04-05T15:00:28.000Z",
  #                 "channelId": "UCnBGS6IXOHsvgDFFKk26WHQ",
  #                 "title": "Say So - 80s Version Doja Cat",
  #                 "description": "Song Suggestions on: https://www.instagram.com/the80sbox https://twitter.com/thedrdee Any questions? Contact me here: Email: deiviprod@gmail.com #dojacat ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/Zbcvx2Ge9x4/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/Zbcvx2Ge9x4/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/Zbcvx2Ge9x4/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "80\'s Box",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/hANVFNQG9Fk-IcMnbotusu8PGrU\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "Ak_MTXQALa0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-06-07T15:00:03.000Z",
  #                 "channelId": "UCWEtnEiVwUy7mwFeshyAWLA",
  #                 "title": "Al Stewart - Year of the Cat (Official Audio)",
  #                 "description": "You\'re listening to the official audio for Al Stewart - \"Year of the Cat\" from the album of the same name. Subscribe to the Rhino Channel!",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/Ak_MTXQALa0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/Ak_MTXQALa0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/Ak_MTXQALa0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "RHINO",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/decGP9meAVaIPTgfW7cH9mTTR7Q\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "VEvhPFpea38"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-04-14T13:00:17.000Z",
  #                 "channelId": "UCGuek8VmKba-TcDUb1agCRw",
  #                 "title": "CÁT BỤI CUỘC ĐỜI  ĐẮP MỘ CUỘC TÌNH  80 Bài BOLERO Nhạc Vàng Xưa LK Nhạc Miền Tây Chọn Lọc 2020 Nghe",
  #                 "description": "Sub ủng hộ kênh nhé cả nhà: http://bit.ly/2EOQgGt Các bạn hãy like& share đăng ký và coment góp ý kiến để kênh ngày một hoàn...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/VEvhPFpea38/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/VEvhPFpea38/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/VEvhPFpea38/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "BOLERO SẾN",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/DJtCpZelmRHWMW5KacHnuYmdDDY\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "zaj1VhS_TxI"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2015-11-06T13:27:45.000Z",
  #                 "channelId": "UCyKs4L4EULCfySbTybA9bAg",
  #                 "title": "Long Train Runnin`  - Curiosity Killed The Cat -  80´s Re:Covered",
  #                 "description": "Written by Tom Johnston. Included in the album “The Captain And Me”. It reached #8 in Billboard Hot 100 (US). It\'s 1993 remix version reached #7 in UK\'s ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/zaj1VhS_TxI/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/zaj1VhS_TxI/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/zaj1VhS_TxI/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Music Brokers",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/4Lyr829_olg9FjPszp7JYlp9NDk\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "vqwKRyb5vIQ"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2013-05-06T20:01:37.000Z",
  #                 "channelId": "UCy-Gbx5DOu7BIiSfdhvp0mg",
  #                 "title": "Assembly Video Go Pet Club Cat Tree - Beige - 80 in.",
  #                 "description": "Learn more about assembling the Go Pet Club Cat Tree from a knowledgeable Hayneedle representative. Shop now at ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/vqwKRyb5vIQ/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/vqwKRyb5vIQ/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/vqwKRyb5vIQ/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "hayneedle.com",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/jfXZQfIznP64PAa40q-YOlUXNiI\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "2gqCL4KGUaw"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-11-26T03:30:01.000Z",
  #                 "channelId": "UCMjf6P1rYTP2S_WX-9rqACg",
  #                 "title": "Colleges To Apply According To CAT %tile [70% 80% 90% Which Colleges Worth To Apply]",
  #                 "description": "Website Link - https://www.learn4exam.com/ TOP 60 MBA COLLEGES - https://youtu.be/aZ_nvQOjBsI CAT FULL SYLLABUS - https://youtu.be/PAQcUA3-684 ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/2gqCL4KGUaw/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/2gqCL4KGUaw/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/2gqCL4KGUaw/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Learn4Exam",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/KpzHf9i9wOHz1XtXDBofwcPvOUk\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "8Iy4tFcwnrU"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2011-03-20T18:49:37.000Z",
  #                 "channelId": "UC6VjaZhMRqWJKDS6OmSaHUA",
  #                 "title": "Me163 mit Turbine Jet Cat 80 Kraftei",
  #                 "description": "Hier ein Flug mit der ME 163 und 80er JetCat Turbine.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/8Iy4tFcwnrU/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/8Iy4tFcwnrU/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/8Iy4tFcwnrU/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Bambelbi1a",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/hENXCrSnE9cs26-nHx5-jEJMGmU\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "-4cFzY4NfCY"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-06-02T21:47:43.000Z",
  #                 "channelId": "UCWDFej82FdZPSjK-mbhvpRA",
  #                 "title": "3119 CAT 80 ARTICULATED GRADER",
  #                 "description": "ARTICULATED MOTOR GRADER WITH CAB AND REAR RIPPER, 1400X24 TIRES, RUNS AND OPERATES WELL.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/-4cFzY4NfCY/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/-4cFzY4NfCY/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/-4cFzY4NfCY/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "wilcox tractor sales",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/-jttQbb4I_zE0ZgbY4-vDDnKln0\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "gTScT1RzSiA"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2020-01-05T08:02:06.000Z",
  #                 "channelId": "UC_D5hKQBzPc2Ilx2gMfl1oA",
  #                 "title": "CAT Percentile vs Colleges. Cut offs from 60%le to 99.99%le",
  #                 "description": "cat2019 #cat2019cutoffs #catcollegescutoffs CAT 99%le ++ https://chat.whatsapp.com/DWhVRGy7yTDAZmmXTadsjj CAT 97-99 Percentilers ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/gTScT1RzSiA/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/gTScT1RzSiA/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/gTScT1RzSiA/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ketankg C2C Mentors",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/9Xp0enTv9vJUQpGrnlfxxuVFBIg\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "A_es8T29hZo"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2015-11-06T13:28:15.000Z",
  #                 "channelId": "UC3-KaS-XEv6atGIHNk2payQ",
  #                 "title": "Long Train Runnin´ - Originally by Doobie Brothers - Curiosity Killed The Cat -  80´s Re:Covered",
  #                 "description": "Written by Tom Johnston. Included in the album “The Captain And Me”. It reached #8 in Billboard Hot 100 (US). It\'s 1993 remix version reached #7 in UK\'s ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/A_es8T29hZo/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/A_es8T29hZo/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/A_es8T29hZo/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "80s Re:Covered",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/huUB-GCJ5Bb9FMcOtBEJqas1KBI\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "PuoOcwGqEgw"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-10-10T12:00:08.000Z",
  #                 "channelId": "UC5BMQOsAB8hKUyHu9KI6yig",
  #                 "title": "My Dear Cat | 고양이는 있다 EP.80 [SUB : ENG,CHN / 2014.10.10]",
  #                 "description": "Multi Language Caption Translation Is Available! Learn How to Activate http://ow.ly/sTv8a 中文字幕，请点击右边下面的Caption按钮。",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/PuoOcwGqEgw/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/PuoOcwGqEgw/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/PuoOcwGqEgw/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "KBS World",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/XoEyGvt223fmJubFYUnVFNrqna8\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "HAwU5vYXns4"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2017-07-11T03:15:13.000Z",
  #                 "channelId": "UCL8SB4eS5JXFWunHUFlLkGQ",
  #                 "title": "80 Cats And Counting: Meet Malaysia&#39;s Ultimate Cat Family",
  #                 "description": "Have you ever wondered what its like to look after over 80 cats? We peek into the lives of Natasha and Natalia Nazli Shah whose family has been caring for their ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/HAwU5vYXns4/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/HAwU5vYXns4/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/HAwU5vYXns4/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Rojak Daily",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/4EfitsZUKdWBUX6VjymotAPl4-E\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "2HsC9V2bXkA"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2013-08-12T22:48:56.000Z",
  #                 "channelId": "UCc0fnVf0OSLDhDPR2yRfg8w",
  #                 "title": "valida occidental cat 80 cc",
  #                 "description": "categoria 80 cc.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/2HsC9V2bXkA/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/2HsC9V2bXkA/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/2HsC9V2bXkA/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "raul soto",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/4v1ABWBk9x8jL_YoJN2OQFmEkxI\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "dPYFV1G2vS8"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-04-28T14:41:37.000Z",
  #                 "channelId": "UCCwXWdQplS9iGCr1ivXHcJg",
  #                 "title": "Grateful Dead - China Cat Sunflower - 10/29/80 - Radio City Music Hall (OFFICIAL)",
  #                 "description": "Grateful Dead - China Cat Sunflower Recorded Live: 10/29/1980 - Radio City Music Hall (New York, NY) More Grateful Dead at Music Vault: ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/dPYFV1G2vS8/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/dPYFV1G2vS8/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/dPYFV1G2vS8/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Music Vault",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/uw87BhK6BoYGpxGlVLzzfL9svGA\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "_S9fXCZ_duA"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2016-07-21T11:50:34.000Z",
  #                 "channelId": "UCX3GDjRMqAIDF1FakrcmccA",
  #                 "title": "Naviják SELLIOR Double Cat 80",
  #                 "description": "http://www.aquazona.cz/e-shop/rybarske-potreby/navijaky-8/navijak-sellior-doublecat-80.html Naviják Sellior DoubleCat je stroj s neuvěřitelnou silou, excelentní ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/_S9fXCZ_duA/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/_S9fXCZ_duA/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/_S9fXCZ_duA/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "AQUAZONA s.r.o.",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/0IbpLWoHEbvsJ9bhQbNgxp2o5cY\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "sXeqpqKgR7w"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2017-10-29T03:46:13.000Z",
  #                 "channelId": "UC59p7Gp75q9x4sW8zGcp0Pw",
  #                 "title": "Filling in sloughs with Cat 80 scraper",
  #                 "description": "Cutting down an old fence line between quarters and filling in a few sloughs.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/sXeqpqKgR7w/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/sXeqpqKgR7w/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/sXeqpqKgR7w/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Saskjdfarmer",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/92AWs9JLicNoQZzCSykAkFHcJR0\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "iqxw8YWMBuk"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2017-08-24T16:12:46.000Z",
  #                 "channelId": "UC-XyYZQKwuvQn_054LwxW1g",
  #                 "title": "Number of attempts for 80%ile in CAT",
  #                 "description": "This is the most common question asked before CAT exam. That\'s a very relative question. It is completely dependent on the difficulty level of the paper.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/iqxw8YWMBuk/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/iqxw8YWMBuk/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/iqxw8YWMBuk/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ck cetking",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/RQbO_LdQ8wOdt4GdOmSuqDEE5F4\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "puNHEHU4ViM"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2018-05-04T13:55:55.000Z",
  #                 "channelId": "UCX1OFSQjlPrpq1Z0v0rdaZA",
  #                 "title": "Gara del 17•02•18 cat.80🔥 1 place🌟 sempre forti noii!!",
  #                 "description": "video del 17 febbraio cat. 80 al prossimo video vi farò vedere la 90 e anche le 100 quando le andrò a fare.",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/puNHEHU4ViM/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/puNHEHU4ViM/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/puNHEHU4ViM/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Maira Charlie",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/od_TzcRFk5smA7qhO9VCTI38dNA\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "JQpge2B1LFk"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2019-01-05T04:58:14.000Z",
  #                 "channelId": "UC-XyYZQKwuvQn_054LwxW1g",
  #                 "title": "CAT 2018 result out. What colleges I can get now!",
  #                 "description": "Call Thane – 0993002806, Vashi – 09820377380, Dadar – 09167917984, Vile Parle – 09833579791, Borivali – 082919 84030, Pune – 09167690141, Nashik ...",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/JQpge2B1LFk/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/JQpge2B1LFk/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/JQpge2B1LFk/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ck cetking",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/fwKTI0t5IJh91SV75tzLhlcWE5I\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "NaXwlWiKiA0"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2012-10-31T19:59:58.000Z",
  #                 "channelId": "UCvSEWIlX-AqNTGhaT_AY2xw",
  #                 "title": "CN JUn 1994 cat 80",
  #                 "description": "Campionatele Nationale de culturism 1994 categoria 80 de kg.Muskiulica junior:))",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/NaXwlWiKiA0/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/NaXwlWiKiA0/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/NaXwlWiKiA0/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "antifotbal",
  #                 "liveBroadcastContent": "none"
  #             }
  #         },
  #         {
  #             "kind": "youtube#searchResult",
  #             "etag": "\"nxOHAKTVB7baOKsQgTtJIyGxcs8/7kjZvd-cyRRXA-jiteeKulPMCQE\"",
  #             "id": {
  #                 "kind": "youtube#video",
  #                 "videoId": "WwYSO1ouyEo"
  #             },
  #             "snippet": {
  #                 "publishedAt": "2014-05-24T12:32:40.000Z",
  #                 "channelId": "UC54XPjsulQTu57c1MsEhV9A",
  #                 "title": "Felix The Cat Episode 80 Final Episode",
  #                 "description": "",
  #                 "thumbnails": {
  #                     "default": {
  #                         "url": "https://i.ytimg.com/vi/WwYSO1ouyEo/default.jpg",
  #                         "width": 120,
  #                         "height": 90
  #                     },
  #                     "medium": {
  #                         "url": "https://i.ytimg.com/vi/WwYSO1ouyEo/mqdefault.jpg",
  #                         "width": 320,
  #                         "height": 180
  #                     },
  #                     "high": {
  #                         "url": "https://i.ytimg.com/vi/WwYSO1ouyEo/hqdefault.jpg",
  #                         "width": 480,
  #                         "height": 360
  #                     }
  #                 },
  #                 "channelTitle": "Ryan Mao",
  #                 "liveBroadcastContent": "none"
  #             }
  #         }
  #     ]
  # }', headers: {})
  # end
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
